import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryClientProvider } from "../../providers/query-client-provider";
import { Toaster } from "sonner";
const noto = localFont({
  src: "./fonts/noto.ttf",
  variable: "--font-noto",
  weight: "100 900", 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${noto.variable} antialiased`}
      >
        <QueryClientProvider>
        {children}
        <Toaster />
        </QueryClientProvider>
        
      </body>
    </html>
  );
}
